### ISSUE TITLE
SCOAP Squad Initialization

### ISSUE THREAD

**Issue by lvnacy** [degen-workgroup/DEGEN#8]
From the Discord:

> A request comes in to the dev team, a SCOAP Squad is created to understand the scope of the work, the work is delegated out, and the SCOAP Squad is dissolved.

This feature is to build out from a web form.

1. Data from the form is caught by DEGEN
2. DEGEN sends a message to the user via Discord for further clarification
3. User responds, data is aggregated and then sent to Notion
4. Once Notion receives the data, messages are fired off to whatever guilds will be involved with the scope of work.

For reference:
![unknown](https://user-images.githubusercontent.com/5085876/120744034-fe049980-c4ae-11eb-8f0e-5f23df575a27.png)

![IMG_4052](https://user-images.githubusercontent.com/5085876/120744020-f80eb880-c4ae-11eb-920b-8bcae4bd3320.jpeg)

**Comment by ZrowGz** [comment]
Per the meeting today, potential use cases for SCOAP integration to the bot:
- listening to other guilds for work being planned for request submission to dev guild, with a reaction to a "SCOAP Squad Assemble" command of sorts
- would return a link to the notion page with instructions on how to submit the request, or perhaps forward the correctly formatted/filled out request into a channel within dev guild discord, or create a pending approval bounty board task
- could include prioritization of request/time frame -- like, if a website is down, that would be a higher priority than creating a new web page for a project in development...
- would be beneficial to have this since it can do 24/7 monitoring

A really important part of this would be making it well known throughout the entire DAO so that people utilize this functionality and don't end up having siloed conversations with external expectations to the dev guild.

Please feel free to correct any part of this that already exists or isn't correct.
